server:
  port: 8081
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  packages-to-scan: com.coder.rental



spring:
  datasource:
    url: jdbc:mysql://172.19.0.2:3306/auto_rental?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    static-path-pattern: /swagger*
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      host: 172.19.0.3
      port: 6379
      database: 0
      timeout: 10000
      expire: 60000
      password: 123456
  mail:
    host: smtp.qq.com
    port: 25
    username: 2297267622@qq.com
    password: hogwpofghiggecih
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.coder.rental.entity
  global-config:
    db-config:
      logic-delete-field: deleted
  #密码加密配置
#密码加密配置
encoder:
  ctype:
    strength: 6
    secret: ${random.uuid}
request:
  login-url: /rental/user/login
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t5p4Tb38EMvuQfJVoFB
    access-key-secret: oKg6ngiKiTagYI44bO6dVuvaAlowOF
    bucket-name: rental-car-test-1
auto:
  info:
    maintain-mileage: 5000

